const data = [
  {
    id: 0,
    name: "Buttermilk Pancakes",
    price: "$15",
    category: "Breakfast",
    info: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
  },
  {
    id: 1,
    name: "Diner Double",
    price: "$15",
    category: "Lunch",
    info: "vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats",
  },
  {
    id: 2,
    name: "Godzilla Milkshake",
    price: "$15",
    category: "Shakes",
    info: "ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.",
  },
  {
    id: 3,
    name: "Country Delight",
    price: "$15",
    category: "Breakfast",
    info: "Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut,",
  },
  {
    id: 4,
    name: "Egg Attack",
    price: "$15",
    category: "Lunch",
    info: "franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up",
  },
  {
    id: 5,
    name: "Oreo Dream",
    price: "$15",
    category: "Shakes",
    info: "Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday",
  },
  {
    id: 6,
    name: "Bacon Overflow",
    price: "$15",
    category: "Breakfast",
    info: "carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird",
  },
  {
    id: 7,
    name: "American Classic",
    price: "$15",
    category: "Lunch",
    info: "on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut",
  },
  {
    id: 8,
    name: "Quarantine Buddy",
    price: "$15",
    category: "Shakes",
    info: "skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.",
  },
];
export default data;
